# Install pre-commit hooks via
# pre-commit install

repos:
  - repo: https://github.com/adamchainz/blacken-docs
    rev: 1.16.0
    hooks:
      - id: blacken-docs
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: \.(html|md|toml|yml|yaml)
        args: [--prose-wrap=preserve]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.8
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format
